// The three sample booklets on the landing page (spec section 14.1). They are
// fixtures rendered by the real renderer, so the samples cannot drift from the
// product: if a variant breaks, the samples break with it.
import type { IssueId } from './layout';
import type { Lang, ThemeId } from './themes';

export interface Sample {
  id: string;
  issue: IssueId;
  theme: ThemeId;
  lang: Lang;
  title: Record<Lang, string>;
  blurb: Record<Lang, string>;
}

export const SAMPLES: Sample[] = [
  {
    id: 'lisbon-en',
    issue: 'lisbon',
    theme: 'lisbon',
    lang: 'en',
    title: { en: 'Lisbon, four days', uk: 'Лісабон, чотири дні' },
    blurb: {
      en: 'Tiles, trams and a pastel de nata a day. Blue duotone photographs, banded cover.',
      uk: 'Плитка, трамваї і паштел-де-ната щодня. Сині дуотонні світлини, смугаста обкладинка.',
    },
  },
  {
    id: 'tokyo-en',
    issue: 'tokyo',
    theme: 'tokyo',
    lang: 'en',
    title: { en: 'Tokyo, four days', uk: 'Токіо, чотири дні' },
    blurb: {
      en: 'Lanterns, towers and a konbini snack at midnight. Black and white, with a local-script echo.',
      uk: 'Ліхтарі, вежі й нічний снек із конбіні. Чорно-біле, з відлунням місцевим письмом.',
    },
  },
  {
    id: 'lisbon-uk',
    issue: 'lisbon',
    theme: 'krakow',
    lang: 'uk',
    title: { en: 'Lisbon in Ukrainian', uk: 'Лісабон українською' },
    blurb: {
      en: 'The same trip, Ukrainian booklet, a different theme. Ukrainian copy runs 15–25% longer and still fits.',
      uk: 'Та сама подорож, український буклет, інша тема. Український текст на 15–25% довший — і все одно вміщається.',
    },
  },
];

export const sampleById = (id: string) => SAMPLES.find((s) => s.id === id);

/** Generated by `pnpm samples` into public/samples. */
export const sampleFiles = (id: string) => ({
  reading: `/samples/${id}-reading.pdf`,
  print: `/samples/${id}-print-A4.pdf`,
});
